### ISSUE TITLE
功能建议：建议做成简单的RESTful API的形式，方便第三方调用

### ISSUE THREAD

**Issue by lgs3137** [yindz/common-random#25]
功能建议：建议做成简单的RESTful API的形式，方便第三方调用

**Comment by yindz** [comment]
你说的是下面的哪一种？
1.做一个简洁的RESTful API后端服务项目?
2.在公网上部署这套服务供第三方调用?

第1个可以做，第2个暂时没有计划(公有云服务器备案、运维成本太高了)

**Comment by lgs3137** [comment]
嗯，能做第一个就足够了~
能实现根据传参随机生成的 一种或多种组合&一条或多条数据

**Comment by lgs3137** [comment]
这样非java的调用就很方便了~

**Comment by yindz** [comment]
第一版的已经搭建好了，可以试试： https://github.com/yindz/common-random-api
