### ISSUE TITLE
Android需要添加implementation 

### ISSUE THREAD

**Issue by AnserBaby** [yindz/common-random#26]
implementation 'org.slf4j:slf4j-api:1.7.25'
    implementation 'com.github.tony19:logback-android:2.0.0'
    implementation 'org.apache.commons:commons-lang3:3.7'
    implementation "com.google.guava:guava:16+"
    implementation 'org.apache.commons:commons-collections4:4.1'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.5'
    Android，其中个人信息不能用

**Comment by yindz** [comment]
个人信息中有个地方用到了awt相关的class，而Android Runtime目前并不支持它。
后续考虑单独做一个兼容Android Runtime的特别版。
