### ISSUE TITLE
非常不错,一个符合中国国情的模拟数据生成,建议发布到maven中央仓库

### ISSUE THREAD

**Issue by ricardo0624** [yindz/common-random#27]
这个需要申请帐号,才能发布,第一次发布可能会麻烦一些

**Comment by ricardo0624** [comment]
查了没查到,还以为没发布呢,乌龙

**Comment by yindz** [comment]
> 查了没查到,还以为没发布呢,乌龙

`<dependency>
    <groupId>com.apifan.common</groupId>
    <artifactId>common-random</artifactId>
    <version>1.0.6</version>
</dependency>`

**Comment by yindz** [comment]
早已发布了，仔细搜
