### ISSUE TITLE
随机日期、时间，能否增加返回Date类型的api

### ISSUE THREAD

**Issue by chy18883701161** [yindz/common-random#48]
目前[生成随机日期](https://github.com/yindz/common-random#%E9%9A%8F%E6%9C%BA%E6%97%A5%E6%9C%9F)返回的是 String，[生成随机时间](https://github.com/yindz/common-random#%E9%9A%8F%E6%9C%BA%E6%97%B6%E9%97%B4)返回的是 LocalDateTime，Date 类型用的较多，再自行转换比较麻烦，能否增加直接返回 Date 的方法？

**Comment by yindz** [comment]
感谢建议。下一版本增加。
