### ISSUE TITLE
虚拟网络昵称 乱码

### ISSUE THREAD

**Issue by en-o** [yindz/common-random#57]
PersonInfoSource.getInstance() .randomChineseNickName(4) 
![image](https://user-images.githubusercontent.com/45027672/177466260-564bfbff-c4ba-49b0-ac90-4331cd354d67.png)

**Comment by yindz** [comment]
getBytes() 的时候传入你想要用的字符集名称，如 
`getBytes("GBK")`

**Comment by yindz** [comment]
注意你getBytes()获取到的byte数组是哪个编码，那么你还原成String的时候也要对应上，就不会出现乱码的情况。

**Comment by yindz** [comment]
> ```java
>  String str1 = new String(name.getBytes("ISO-8859-1"), "utf-8");
>         System.out.println(str1);
>         String str2 = new String(name.getBytes("gb2312"), "utf-8");
>         System.out.println(str2);
>         String str3 = new String(name.getBytes("gbk"), "utf-8");
>         System.out.println(str3);
> ```
> 
> 试完了都不行

例如：
`String str2 = new String(name.getBytes("GBK"), "GBK");`
